#!/usr/bin/env node
// tools/security_os/gen_proposed_docs.mjs — generates proposed canonical docs (MP49). Read-only.
// Writes ONLY under docs_canonical_proposed/. Does NOT apply.
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.cwd(), 'docs_canonical_proposed');
const SUB = '16_security';

const DOCS = [
  ['security_control_plane_note.md', 'Security Control Plane — Canonical Note', '16_security/security_control_plane_note.md', 'Security / Privacy / Compliance Control Plane: security governance, asset inventory, threat model, ownership, access/role/capability policy, secrets policy, credential lifecycle, data classification, privacy minimization, retention, audit, security verification gates, incident response, vulnerability + supply-chain policy, security evidence, compliance control mapping. NOT a SIEM/firewall/password-manager/legal-advisor. Never stores real secret values, uses/rotates credentials, scans live hosts, sends, mutates production, deletes files, or asserts legal compliance.'],
  ['security_asset_registry.md', 'Security Asset Registry', '16_security/security_asset_registry.md', '12 assets (VPS, canonical store, MC API, SSH/Telegram/IMAP/SMTP/Android-signing secrets, File Vault, Git repo, backups, agent environment, Android client) with owner/criticality/CIA/data-classes/boundaries/controls/gaps.'],
  ['threat_model.md', 'Threat Model', '16_security/threat_model.md', '12 threats by trust boundary across STRIDE + supply-chain + prompt-injection + data-exfiltration + unsafe-automation. Each: precondition/impact/likelihood/controls/gaps/mitigation/owner/verification/status. No live attack testing.'],
  ['security_ownership_matrix.md', 'Security Ownership Matrix', '16_security/security_ownership_matrix.md', 'Exactly one owner per decision: policy/secret/credential/role/service-identity/vulnerability/incident/audit-event/exception/classification/retention/deletion/backup-encryption/release-gate. Audit event -> Master Controller (no second ledger).'],
  ['identity_role_standard.md', 'Identity and Role Standard', '16_security/identity_role_standard.md', '12 identities + 10 roles (OWNER/SECURITY_ADMIN_FUTURE/DEVELOPER_AGENT/READ_ONLY_ANALYST/API_SERVICE/WORKER_SERVICE/TELEGRAM_SERVICE/IMAP_READ_ONLY_SERVICE/ANDROID_CLIENT/BACKUP_SERVICE). No role grants by implementation in this task.'],
  ['least_privilege_policy.md', 'Least Privilege Policy', '16_security/least_privilege_policy.md', 'Per-identity allowed systems/data-classes/read/write/execute/network/secret/canonical/send/deploy/backup/restore + owner gate. Boundary assertions: Telegram no canonical/secret, IMAP read-only, Android no server secrets, agent no production/network, Conversation Hub no send, Analytics no domain write, Lead Hunter no canonical write.'],
  ['authentication_standard.md', 'Authentication Standard', '16_security/authentication_standard.md', 'Per-identity credential_type/storage_reference/rotation/expiry/scope/revocation/audit/fallback. Fail-closed. No actual credential generation.'],
  ['authorization_standard.md', 'Authorization Standard', '16_security/authorization_standard.md', 'Deny-by-default; explicit capability+resource+operation+environment+owner-gate+revision+audit. Detects role-too-broad/wildcard/unnecessary-send/unnecessary-canonical-write/offline-mutation/hidden-fallback.'],
  ['secrets_management_policy.md', 'Secrets Management Policy', '16_security/secrets_management_policy.md', '8 secret categories. Never Git/report/context-pack/fixture/log; reference only; environment separation; least privilege; rotation; revocation; fingerprint without value; owner-gated access.'],
  ['credential_lifecycle.md', 'Credential Lifecycle', '16_security/credential_lifecycle.md', 'REQUESTED..DESTROYED_CONFIRMED. Rotation runbooks for SSH/Telegram/IMAP/SMTP/signing/external (owner-gated, no automation). Signing-key rotation breaks Android update path -> owner+legal.'],
  ['secure_configuration_standard.md', 'Secure Configuration Standard', '16_security/secure_configuration_standard.md', 'Env vars for secrets, root-only files, redacted diagnostics, safe defaults, fail-closed, no inappropriate localhost fallback, HTTPS-only. Static validation.'],
  ['data_classification_mapping.md', 'Data Classification Mapping', '16_security/data_classification_mapping.md', 'Reuses Integration 9 classes. Maps leads/contacts/audit/messages/attachments/invoices/health/legal/credentials/logs/backups/analytics/synthetic. No raw sensitive examples in fixtures.'],
  ['privacy_minimization_policy.md', 'Privacy Minimization Policy', '16_security/privacy_minimization_policy.md', 'Collect minimum, stable IDs, avoid copying bodies, redact contacts, aggregate analytics, separate operational/analytics, exclude special-category from context packs, no production data in fixtures, purpose+access limitation.'],
  ['consent_optout_reconciliation.md', 'Consent / Opt-out Reconciliation', '16_security/consent_optout_reconciliation.md', 'Reconciles Conversation Hub / Growth / Customer Success / Revenue / Master Controller / Analytics. Purposes separated; no implied consent; opt-out canonical owner = Master Controller; no automatic legal conclusion.'],
  ['privacy_impact_framework.md', 'Privacy Impact Framework', '16_security/privacy_impact_framework.md', 'PIA per processing activity (lead discovery/email monitoring/android cache/financial). Status INTERNAL_CONTROL/OWNER_REVIEW_REQUIRED/LEGAL_REVIEW_REQUIRED/NOT_ASSESSED. Does not claim legal compliance.'],
  ['retention_deletion_policy.md', 'Retention / Deletion Policy', '16_security/retention_deletion_policy.md', 'Retention per data type. Deletion stages REQUESTED..VERIFIED; max READY this task; no deletion. Opt-outs indefinite suppression; invoices statutory legal review.'],
  ['encryption_standard.md', 'Encryption Standard', '16_security/encryption_standard.md', 'In-transit (HTTPS/SSH/IMAPS/SMTPS) + at-rest (workstation/VPS/backups/Android/vault/signing). Status CONFIRMED_DOCUMENTED/REQUIRES_LIVE_VERIFICATION/PLANNED/UNKNOWN. No encryption claimed on assumption.'],
  ['logging_redaction_standard.md', 'Logging / Redaction Standard', '16_security/logging_redaction_standard.md', 'Allowed fields (request-id/operation/entity-id/status/duration/error-code/service/timestamp/redacted-ref). Forbidden: secret/token/password/raw-auth/private-key/full-body/unnecessary-contact/financial-credential/attachment-body.'],
  ['audit_trail_standard.md', 'Audit Trail Standard', '16_security/audit_trail_standard.md', '16 audit event types. Append-only; not modifiable by derived UI; no second outbound ledger; owner-readable.'],
  ['application_security_standard.md', 'Application Security Standard', '16_security/application_security_standard.md', 'Input validation, output encoding, command-injection, path-traversal, deserialization, prototype-pollution, ReDoS, SSRF, open-redirect, file-upload, MIME, size, archive-bomb, temp-files, shell, subprocess. Static + safe synthetic tests.'],
  ['api_security_standard.md', 'API Security Standard', '16_security/api_security_standard.md', 'HTTPS-only, auth required, authorization, revision, idempotency, validation, rate-limit, replay protection, structured errors, no stack traces, no secrets, pagination/body bounds, timeout, correlation. No production API change.'],
  ['prompt_injection_policy.md', 'Agent / Prompt Injection Policy', '16_security/prompt_injection_policy.md', '9 threats + controls (instruction hierarchy, source trust classification, allowed-path, capability gate, secret exclusion, output validation, no auto-exec, owner approval, deterministic verification). Client message + web content + tool output = UNTRUSTED.'],
  ['data_exfiltration_policy.md', 'Data Exfiltration Policy', '16_security/data_exfiltration_policy.md', 'Blocks secrets in reports, credentials in context packs, production files in fixtures, full bodies in analytics, real contacts in demos, financial data in logs, special-category in prompts, uploads without approval. Static validation.'],
  ['dependency_supply_chain_policy.md', 'Dependency / Supply Chain Policy', '16_security/dependency_supply_chain_policy.md', 'SBOM-like inventory (component/version/ecosystem/source/license/usage/network/review/update-policy). No live vuln lookup, no package update unless required + proven safe.'],
  ['file_attachment_security.md', 'File / Attachment Security', '16_security/file_attachment_security.md', 'MIME allowlist, extension mismatch, max size, checksum, archive handling, path normalization, traversal prevention, executable detection, macro handling, malware-scan future, quarantine, File Vault reference. No real upload.'],
  ['android_security_reconciliation.md', 'Android Security Reconciliation', '16_security/android_security_reconciliation.md', 'HTTPS-only, no server secrets, Room cache classified PERSONAL, cache encryption REQUIRES_LIVE_VERIFICATION, no sensitive logging, external signing, no offline mutation, revision, cert validation, debug separation. No build modification.'],
  ['telegram_security_reconciliation.md', 'Telegram Security Reconciliation', '16_security/telegram_security_reconciliation.md', 'Owner identity, API-only, token isolation (env), callback validation, revision, idempotency, no local file access, no raw object/secret output, no client send from owner UI, one poller, service-user permissions. No API call/deploy.'],
  ['email_imap_security.md', 'Email / IMAP Security', '16_security/email_imap_security.md', 'Read-only IMAP source: explicit read-only, no flag mutation/send/APPEND/DELETE/expunge, TLS, env credential reference, timeout, bounded reads, body minimization, failure redaction. Approved transport reviewed separately. Neither executed.'],
  ['conversation_hub_security.md', 'Conversation Hub Security', '16_security/conversation_hub_security.md', 'Identity conflict blocks routing, recipient evidence, opt-out enforced, draft validation, approval reference only, no direct transport, redaction, retention, attachment references, official-channel-only, no unofficial WhatsApp/MAX.'],
  ['orchestration_security.md', 'Orchestration Security', '16_security/orchestration_security.md', 'R3+ owner gate, no agent self-approval, capability restrictions, no secret access, no production executor, no scheduler, bounded retries, lease, checkpoint, artifact sensitivity, context minimization, prompt-injection policy, token/cost integrity.'],
  ['backup_security.md', 'Backup Security', '16_security/backup_security.md', 'Classification CONFIDENTIAL, owner access, SHA256 integrity, encryption PLANNED, off-site owner-defined, rotation retention, owner-gated restore, no secret inclusion, no real production data in tracked backup, test restore, owner-gated deletion.'],
  ['incident_response.md', 'Security Incident Response', '16_security/incident_response.md', '12 incident types, lifecycle DETECTED..CLOSED. Runbooks (credential leak never prints value + owner-gated rotation; git-history leak; prompt-injection; VPS compromise). Synthetic only.'],
  ['vulnerability_management.md', 'Vulnerability Management', '16_security/vulnerability_management.md', 'Model (id/asset/source/severity/exploitability/exposure/evidence/status/mitigation/verification/exception/owner). Statuses NEW..VERIFIED. No live scanning.'],
  ['security_exception_policy.md', 'Security Exception Policy', '16_security/security_exception_policy.md', 'Exception requires control/reason/asset/risk/compensating-control/owner/expiry/review/evidence. No permanent exception without expiry/review. Agent cannot approve.'],
  ['compliance_control_mapping.md', 'Compliance Control Mapping', '16_security/compliance_control_mapping.md', '12 control areas with status IMPLEMENTED_AND_TESTED/DOCUMENTED_ONLY/PARTIAL/MISSING/NOT_APPLICABLE/LEGAL_REVIEW_REQUIRED. Jurisdiction-neutral. Does NOT claim GDPR/152-FZ/ISO/fully-compliant.'],
  ['security_release_gate.md', 'Security Release Gate', '16_security/security_release_gate.md', 'Requires no critical secret finding, no tracked live secret, no unauthorized writer, no send bypass, security+privacy tests pass, dependency inventory, backup/restore evidence, rollback, owner approval, exceptions listed. Statuses NOT_READY/BLOCKED/READY_FOR_OWNER_REVIEW/OWNER_ACCEPTED_REFERENCE.'],
  ['security_dashboard.md', 'Security Dashboard', '09_dashboards/security_dashboard.md', 'Critical assets, trust boundaries, open findings, secret findings, sensitive-data findings, access risks, supply-chain risks, communication-monitor disposition, incidents, exceptions, release gate, owner actions, controls requiring legal review.'],
  ['owner_security_command_center.md', 'Owner Security Command Center', '09_dashboards/owner_security_command_center.md', 'Highest security risk, tracked-secret status, files requiring disposition, credential rotation proposals, unresolved access issue, privacy review, release blocker, owner approval, legal-review item, next safe action.'],
  ['communication_monitor_disposition_plan.md', 'Communication Monitor Disposition Plan', '16_security/communication_monitor_disposition_plan.md', '21 excluded files classified: KEEP_RESTRICTED=3, KEEP_AUDIT_EVIDENCE=5, REDACT_AND_TRACK=4, MOVE_TO_QUARANTINE=4, MOVE_TO_ARCHIVE=4, DELETE_AFTER_APPROVAL=1, ROTATION_REQUIRED=0. No literal secret found. Send scripts + real-email result JSONs quarantined. Owner approval required; no file deleted/moved.'],
  ['what_already_exists_links.md', 'WHAT_ALREADY_EXISTS + AI System Map Links', '16_security/what_already_exists_links.md', 'Security Control Plane adds governance/threat/secrets/privacy/retention/audit/incident/compliance over the existing chain. Reuses Integration data classes + Orchestration capability gates + existing per-OS security tests + 05_security/security_gate.md. Links: tools/security_os/, _generated/security_os/.'],
  ['secret_reference_registry.md', 'Secret Reference Registry', '16_security/secret_reference_registry.md', 'Reference-only registry of secret TYPES + storage references + rotation policy. NEVER contains a value. Fingerprint-only on detection.'],
  ['prompt_injection_report.md', 'Prompt Injection Report', '16_security/prompt_injection_report.md', 'Synthetic attack fixtures (client-message + repo-file injection, agent-asks-secret, agent-network) each blocked by a named control. No real exploit.'],
  ['security_boundary_report.md', 'Security Boundary Report', '16_security/security_boundary_report.md', 'Proves the security_os tree itself: no network/send/production/delete/merge/live-scan, no real secret value, no real contacts, no legal-compliance assertion. Self-test catches planted real secret in data.'],
];

mkdirSync(path.join(ROOT, SUB), { recursive: true });
let count = 0;
for (const [file, title, target, body] of DOCS) {
  const dir = target.includes('/') ? path.dirname(target) : SUB;
  mkdirSync(path.join(ROOT, dir), { recursive: true });
  const md = `---\ncanonical_target: ${target}\nrelated_project: security-control-plane\nstatus: PROPOSED_NOT_APPLIED\nsynthetic: true\n---\n\n# ${title}\n\n${body}\n\n> Proposed canonical doc. NOT applied. Owner applies post-review via AI HQ apply flow.\n`;
  writeFileSync(path.join(ROOT, dir, file), md);
  count++;
}
console.log(`[gen-proposed-docs] wrote ${count} security proposed docs under docs_canonical_proposed/`);
