// tools/ai_hq/lib/projects.mjs
// Canonical project model for AI Operations HQ.
// Seeded from the existing PROJECT_REGISTRY + real workspace dirs (evidence-based).
// Statuses/priorities use the unified vocabularies from the consolidation spec.

export const STATUS = {
  ACTIVE_PRODUCTION: 'ACTIVE_PRODUCTION',
  ACTIVE_DEVELOPMENT: 'ACTIVE_DEVELOPMENT',
  ACCEPTANCE: 'ACCEPTANCE',
  PAUSED: 'PAUSED',
  BLOCKED_EXTERNAL: 'BLOCKED_EXTERNAL',
  PLANNED: 'PLANNED',
  MAINTENANCE: 'MAINTENANCE',
  ARCHIVED: 'ARCHIVED',
  SENSITIVE_READ_ONLY: 'SENSITIVE_READ_ONLY',
  UNKNOWN: 'UNKNOWN',
};

export const PRIORITY = {
  P0_CRITICAL: 'P0_CRITICAL',
  P1_REVENUE: 'P1_REVENUE',
  P2_INFRASTRUCTURE: 'P2_INFRASTRUCTURE',
  P3_PRODUCTIVITY: 'P3_PRODUCTIVITY',
  P4_RESEARCH: 'P4_RESEARCH',
  P5_ARCHIVE: 'P5_ARCHIVE',
};

// Evidence-based seed. `paths` are scanned to confirm existence + last_modified.
// No invented projects: every entry maps to a real folder/registry row.
export const PROJECT_SEED = [
  {
    project_id: 'master_controller',
    name: 'Master Controller (release v0.4.0-rc1)',
    category: 'platform',
    status: STATUS.ACCEPTANCE,
    priority: PRIORITY.P0_CRITICAL,
    production_state: 'PRODUCTION_SOAK',
    paths: ['tools/master_controller', 'tools/mater_controller_api', '00_MASTER_CONTROLLER'],
    source_of_truth: 'VPS Master Controller API + canonical JSON store (13_sales/lead_pipeline_store.json)',
    agent_owner: 'claude',
    risk: 'high',
    next_major_action: 'Complete 24h no-send soak; owner acceptance; then controlled production prep',
    blockers: ['24h soak in progress (FREEZE)'],
    secrets_required: true,
  },
  {
    project_id: 'telegram_master_controller',
    name: 'Telegram Master Controller (API-only backup interface)',
    category: 'interface',
    status: STATUS.ACTIVE_PRODUCTION,
    priority: PRIORITY.P0_CRITICAL,
    production_state: 'LIVE_BACKUP_CHANNEL',
    paths: ['tools/telegram_gateway'],
    source_of_truth: 'tools/telegram_gateway (shared Mini Audit services)',
    agent_owner: 'claude',
    risk: 'high',
    next_major_action: 'No UX changes until soak closes (FREEZE)',
    blockers: ['Soak freeze'],
    secrets_required: true,
  },
  {
    project_id: 'android_master_controller',
    name: 'Mater Controller Android (primary owner interface)',
    category: 'interface',
    status: STATUS.ACCEPTANCE,
    priority: PRIORITY.P1_REVENUE,
    production_state: 'RELEASE_CANDIDATE',
    paths: ['apps/mater_controller_android', 'dist/mater_controller_android'],
    source_of_truth: 'apps/mater_controller_android + Mater Controller API',
    agent_owner: 'claude',
    risk: 'high',
    next_major_action: 'Owner/device smoke; release closure after soak',
    blockers: ['Soak freeze', 'Release APK/AAB frozen'],
    secrets_required: true,
  },
  {
    project_id: 'mini_audit_10k',
    name: 'Mini Audit 10K',
    category: 'revenue',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P1_REVENUE,
    production_state: 'BUILD_TEST',
    paths: ['06_projects/mini_audit_10k', '13_sales'],
    source_of_truth: '13_sales/lead_pipeline_store.json (canonical lead store)',
    agent_owner: 'claude',
    risk: 'medium',
    next_major_action: 'Pick one USE_NOW deliverable (no send)',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'lead_hunter',
    name: 'Lead Hunter (discovery intelligence)',
    category: 'intelligence',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P2_INFRASTRUCTURE,
    production_state: 'BUILD_TEST',
    paths: ['tools/lead_hunter'],
    source_of_truth: 'tools/lead_hunter (single Overpass implementation)',
    agent_owner: 'claude',
    risk: 'medium',
    next_major_action: 'Credentials decision for 2GIS/DataForSEO/Yandex (owner)',
    blockers: ['External API credentials (owner action)'],
    secrets_required: true,
  },
  {
    project_id: 'obsidian_hq',
    name: 'Obsidian / AI_WORKSPACE HQ',
    category: 'infrastructure',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P1_REVENUE,
    production_state: 'OPERATIONAL',
    paths: ['00_MASTER_CONTEXT', '09_dashboards', '03_sop', '06_projects/obsidian_hq'],
    source_of_truth: '00_MASTER_CONTEXT/PROJECT_REGISTRY.md + WHAT_ALREADY_EXISTS.md',
    agent_owner: 'claude',
    risk: 'low',
    next_major_action: 'Maintain; one real task at a time',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'reminder_secretary',
    name: 'Reminder Secretary OS',
    category: 'productivity',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P3_PRODUCTIVITY,
    production_state: 'OBSIDIAN_ONLY',
    paths: ['12_reminders', '06_projects/reminder_secretary'],
    source_of_truth: '12_reminders/',
    agent_owner: 'cline',
    risk: 'low',
    next_major_action: 'Review reminders/deadlines',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'file_vault',
    name: 'Personal File Vault (index-only)',
    category: 'infrastructure',
    status: STATUS.MAINTENANCE,
    priority: PRIORITY.P2_INFRASTRUCTURE,
    production_state: 'INDEX_ONLY',
    paths: ['20_file_vault_index', '06_projects/file_vault'],
    source_of_truth: '20_file_vault_index/ (large files live in D:\\AI_FILE_VAULT)',
    agent_owner: 'cline',
    risk: 'medium',
    next_major_action: 'Index only when new files arrive; dry-run intake',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'revenue_os',
    name: 'Revenue OS / Sales',
    category: 'revenue',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P1_REVENUE,
    production_state: 'INDEX',
    paths: ['07_revenue_os', '13_sales'],
    source_of_truth: '07_revenue_os/revenue_os_structure.md',
    agent_owner: 'claude',
    risk: 'low',
    next_major_action: 'Safe dashboards/summaries only (no outreach)',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'kgbi_b2b_audit',
    name: 'КЖБИ B2B Audit',
    category: 'revenue',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P2_INFRASTRUCTURE,
    production_state: 'BUILD_TEST',
    paths: ['06_projects/kgbi_b2b_audit'],
    source_of_truth: '06_projects/kgbi_b2b_audit/PROJECT_PASSPORT.md',
    agent_owner: 'claude',
    risk: 'low',
    next_major_action: 'Review audit_plan; confirm deliverable scope',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'edera_rest_mini_audit',
    name: 'Edera Rest Mini Audit',
    category: 'revenue',
    status: STATUS.PAUSED,
    priority: PRIORITY.P3_PRODUCTIVITY,
    production_state: 'BUILD',
    paths: ['06_projects/edera_rest_mini_audit'],
    source_of_truth: '06_projects/edera_rest_mini_audit/PROJECT_PASSPORT.md',
    agent_owner: 'claude',
    risk: 'low',
    next_major_action: 'Confirm status; decide go/hold',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'lead_gen_test_jbi',
    name: 'JBI Krasnodar Lead-Gen Test',
    category: 'revenue',
    status: STATUS.PAUSED,
    priority: PRIORITY.P3_PRODUCTIVITY,
    production_state: 'TEST',
    paths: ['06_projects/lead_gen_test_jbi'],
    source_of_truth: '06_projects/lead_gen_test_jbi/PROJECT_PASSPORT.md',
    agent_owner: 'claude',
    risk: 'low',
    next_major_action: 'Decide if test concludes or scales (outreach approval)',
    blockers: ['Outreach approval (owner)'],
    secrets_required: false,
  },
  {
    project_id: 'chatgpt_pipeline',
    name: 'ChatGPT Export/Import Pipeline',
    category: 'infrastructure',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P3_PRODUCTIVITY,
    production_state: 'TOOLING',
    paths: ['tools/chatgpt_export', '00_IMPORTS', '98_raw_chat_exports'],
    source_of_truth: 'tools/chatgpt_export + 00_IMPORTS',
    agent_owner: 'cline',
    risk: 'low',
    next_major_action: 'Offline idempotent import pipeline (fixtures first)',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'backup_dr',
    name: 'Backup / Disaster Recovery',
    category: 'infrastructure',
    status: STATUS.MAINTENANCE,
    priority: PRIORITY.P2_INFRASTRUCTURE,
    production_state: 'OPERATIONAL',
    paths: ['tools/backups', '11_backup', '00_BACKUPS'],
    source_of_truth: 'D:\\AI_BACKUPS + git bundles',
    agent_owner: 'claude',
    risk: 'medium',
    next_major_action: 'Manifest + checksum + restore proof; RPO/RTO targets',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'local_ai_hq',
    name: 'Local AI models / future HQ workstation',
    category: 'research',
    status: STATUS.PLANNED,
    priority: PRIORITY.P4_RESEARCH,
    production_state: 'PLANNING',
    paths: ['10_local_ai'],
    source_of_truth: '10_local_ai/',
    agent_owner: 'owner',
    risk: 'low',
    next_major_action: 'Workstation plan (90-day)',
    blockers: ['Hardware decision (owner)'],
    secrets_required: false,
  },
  {
    project_id: 'cline_integration',
    name: 'Cline Integration (focused local executor)',
    category: 'infrastructure',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P3_PRODUCTIVITY,
    production_state: 'OPERATIONAL',
    paths: ['04_cline', '.clinerules'],
    source_of_truth: '04_cline/CLINE_OPERATING_LAYER_INDEX.md',
    agent_owner: 'cline',
    risk: 'low',
    next_major_action: 'Use context packs + handoff protocol',
    blockers: [],
    secrets_required: false,
  },
  {
    project_id: 'claude_code_integration',
    name: 'Claude Code Integration (large-block implementer)',
    category: 'infrastructure',
    status: STATUS.ACTIVE_DEVELOPMENT,
    priority: PRIORITY.P3_PRODUCTIVITY,
    production_state: 'OPERATIONAL',
    paths: ['.claude', 'tools/ai_hq'],
    source_of_truth: 'tools/ai_hq + governance SOP',
    agent_owner: 'claude',
    risk: 'low',
    next_major_action: 'Use context pack builder + task ledger',
    blockers: [],
    secrets_required: false,
  },
];

// Sensitive container-only projects (no detailed summaries, never in shared context packs).
export const SENSITIVE_SEED = [
  { project_id: 'legal_documents', name: 'Legal Documents', paths: ['15_legal_documents'] },
  { project_id: 'personal_assistant', name: 'Personal Assistant (personal data)', paths: ['13_personal_assistant'] },
  { project_id: 'file_vault_red', name: 'File Vault RED (military/medical/identity)', paths: ['20_file_vault_index'] },
].map((p) => ({
  ...p,
  category: 'sensitive',
  status: STATUS.SENSITIVE_READ_ONLY,
  priority: PRIORITY.P5_ARCHIVE,
  production_state: 'INDEX_ONLY',
  source_of_truth: 'container index only',
  agent_owner: 'owner',
  risk: 'high',
  next_major_action: 'No content access without explicit owner request',
  blockers: ['Owner-only'],
  secrets_required: false,
  sensitive: true,
}));

// Placeholder/empty projects from registry (tracked, not invented).
export const PLACEHOLDER_SEED = [
  { project_id: 'boxon', name: 'BOXON (шины/хранение)', paths: ['18_boxon'] },
  { project_id: 'kgbi_standalone', name: 'КЖБИ (standalone)', paths: ['19_kgbi'] },
  { project_id: 'project_maria', name: 'Проект Марии', paths: ['20_project_maria'] },
  { project_id: 'strength_form_35', name: 'Силовая форма 35+', paths: ['21_strength_form_35', '16_fitness_products'] },
  { project_id: 'ai_content_factory', name: 'AI Content Factory', paths: ['14_content_factory'] },
].map((p) => ({
  ...p,
  category: 'placeholder',
  status: STATUS.PLANNED,
  priority: PRIORITY.P5_ARCHIVE,
  production_state: 'PLACEHOLDER',
  source_of_truth: 'folder (placeholder)',
  agent_owner: 'owner',
  risk: 'low',
  next_major_action: 'Activate only when real files exist',
  blockers: [],
  secrets_required: false,
}));

export function allSeeds() {
  return [...PROJECT_SEED, ...SENSITIVE_SEED, ...PLACEHOLDER_SEED];
}
