#!/usr/bin/env node
// tools/orchestrator_os/gen_proposed_docs.mjs — generates proposed canonical docs (MP44). Read-only.
// Writes ONLY under docs_canonical_proposed/. Does NOT apply.
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.cwd(), 'docs_canonical_proposed');
const SUB = '15_agent_orchestration';

const DOCS = [
  ['agent_orchestration_note.md', 'Agent Orchestration — Canonical Note', '15_agent_orchestration/agent_orchestration_note.md', 'Agent Automation & Orchestration is a development/knowledge-work control plane for AI-agent tasks: task contracts, agent/model selection, capability policy, execution plans, dependency DAG, anti-loop, checkpoints, budgets, leases, retries, dead-letter, artifact handoff, verification, owner gates, audit. It is NOT a production worker/scheduler and NOT a replacement for the Master Controller job queue. It never starts real agents, schedulers, background processes, networks, sends, or mutates production. Max executable risk this block: R2_ISOLATED_CODE.'],
  ['task_contract_standard.md', 'Task Contract Standard', '15_agent_orchestration/task_contract_standard.md', '17 required sections: objective, current_state, source_of_truth, exact_scope, out_of_scope, allowed_paths, forbidden_paths, allowed_tools, forbidden_tools, safety_invariants, required_phases, tests, commit_gates, deployment_gate, stop_conditions, done_definition, final_report_schema.'],
  ['risk_model.md', 'Risk Model', '15_agent_orchestration/risk_model.md', 'R0_READ_ONLY..R6_EXTERNAL_COMMUNICATION. Block max executable = R2_ISOLATED_CODE; R3+ are contract/policy/owner-gated only.'],
  ['capability_registry.md', 'Capability Registry', '15_agent_orchestration/capability_registry.md', '17 capabilities with risk, allowed agents, owner gate, environment, audit. mutate_canonical/deploy/restart/send/publish/push are HUMAN_OWNER only.'],
  ['agent_selection_policy.md', 'Agent Selection Policy', '15_agent_orchestration/agent_selection_policy.md', 'Deterministic tools for validation/transform/reports; Claude Code for repo-wide; Cline for file-local; human owner for price/capacity/production/external/credentials/git-remote/legal/delete. No convenience-only selection.'],
  ['model_routing_policy.md', 'Model Routing Policy', '15_agent_orchestration/model_routing_policy.md', 'Routing by risk/context/breadth/deterministic-alternative/privacy/budget/tools. Critical tasks cannot auto-route to unverified local model. No real model API calls.'],
  ['context_pack_contract.md', 'Context Pack Contract', '15_agent_orchestration/context_pack_contract.md', 'Reuses AI HQ context_pack_builder. Requires project/task/source-commits/canonical-files/decisions/completed-work/risks/forbidden-actions/budget/freshness/checksums/secret+sensitive exclusion. Prevents whole-repo dumps, stale/duplicate context, secrets.'],
  ['dependency_policy.md', 'Dependency DAG Policy', '15_agent_orchestration/dependency_policy.md', 'DAG with cycle/missing/failed/stale/superseded/owner/freeze detection. Task cannot run if a required dependency is incomplete.'],
  ['anti_loop_policy.md', 'Anti-loop Policy', '15_agent_orchestration/anti_loop_policy.md', 'Detects duplicate/repeated-failed-approach/already-completed/superseding/equivalent-branch. Actions: CONTINUE/RESUME/REUSE/SUPERSEDE/BLOCK_DUPLICATE/REQUIRE_NEW_EVIDENCE/OWNER_REVIEW.'],
  ['plan_standard.md', 'Plan Standard', '15_agent_orchestration/plan_standard.md', 'Phased plans (objective/inputs/outputs/files/commands/risk/verification/checkpoint/continuation). Agent must not stop after each safe phase.'],
  ['approval_gate_policy.md', 'Approval Gate Policy', '15_agent_orchestration/approval_gate_policy.md', '11 gate categories. Approval is a REFERENCE to an authoritative Executive/owner decision, never a boolean invented by the agent. No agent self-approval.'],
  ['budget_policy.md', 'Budget Policy', '15_agent_orchestration/budget_policy.md', 'token/monetary/time/files/commands/retries/parallelism/context budgets. Statuses UNKNOWN/OWNER_TARGET/ESTIMATED/OBSERVED/EXCEEDED. No fabricated confirmed cost. Breach -> checkpoint+stop+evidence+reduced-scope.'],
  ['lease_policy.md', 'Lease Policy', '15_agent_orchestration/lease_policy.md', 'One active writer lease per isolated worktree; expired recoverable; no duplicate run; no production locks; synthetic simulator only.'],
  ['checkpoint_resume_policy.md', 'Checkpoint / Resume Policy', '15_agent_orchestration/checkpoint_resume_policy.md', 'Checkpoint = completed phases/branch/commit/dirty/tests/artifacts/decisions/blockers/next/state-hash. Resume validates branch/commits/files/dependencies unchanged.'],
  ['retry_policy.md', 'Retry Policy', '15_agent_orchestration/retry_policy.md', '9 failure classes. No retry for POLICY_BLOCK/OWNER_REQUIRED/TERMINAL. Bounded; change strategy after repeated identical; ambiguous -> reconcile.'],
  ['dead_letter_policy.md', 'Dead Letter Policy', '15_agent_orchestration/dead_letter_policy.md', 'Dead-letter = task/run/attempts/failure/evidence/artifacts/recovery options/owner action. No automatic production recovery.'],
  ['cancellation_policy.md', 'Cancellation / Pause Policy', '15_agent_orchestration/cancellation_policy.md', 'Cancellation preserves evidence, records reason, invalidates lease, deletes nothing, resets no canonical state. Pause requires checkpoint + resume conditions.'],
  ['artifact_handoff_standard.md', 'Artifact Handoff Standard', '15_agent_orchestration/artifact_handoff_standard.md', 'Artifacts (code/report/fixture/test/backup/bundle/proposed-docs/migration/release) carry hash/source-run/sensitivity/verification/retention/consumer. None canonical.'],
  ['verification_standard.md', 'Verification Standard', '15_agent_orchestration/verification_standard.md', 'Gate types syntax/unit/integration/security/privacy/no-network/no-send/no-production/backup/restore/source-match/owner-acceptance. Agent claim insufficient — command+result+evidence required.'],
  ['quality_standard.md', 'Quality Standard', '15_agent_orchestration/quality_standard.md', 'Dimensions: objective completion, SoT compliance, test evidence, safety, determinism, reproducibility, regression, docs, rollback, unresolved risk. Score cannot hide a hard blocker.'],
  ['agent_handoff_standard.md', 'Agent Handoff Standard', '15_agent_orchestration/agent_handoff_standard.md', 'Claude<->Cline, deterministic->Claude, agent->owner, agent->future worker. Package: task/completed-work/branch+commit/artifacts/tests/unresolved/next-action/forbidden-actions/context-checksum.'],
  ['scheduler_contract.md', 'Scheduler Contract', '15_agent_orchestration/scheduler_contract.md', 'Future scheduler: select READY -> enforce dependency -> acquire lease -> enforce capability/budgets -> invoke approved executor -> persist checkpoints -> verify -> release lease. This task: contract + simulator only. No cron/systemd/Windows task.'],
  ['executor_contracts.md', 'Executor Contracts', '15_agent_orchestration/executor_contracts.md', 'Claude Code / Cline / deterministic Node / deterministic Python / human executors. No subprocess starts Claude/Cline. I/O envelope follows the Integration API standard.'],
  ['production_queue_boundary.md', 'Production Queue Boundary', '15_agent_orchestration/production_queue_boundary.md', 'Orchestration = development/docs/analysis/offline/proposed. Master Controller queue = production pipeline/operational jobs/canonical mutations. No shared writable queue; future handoff only via approved contract.'],
  ['token_cost_accounting.md', 'Token / Cost Accounting', '15_agent_orchestration/token_cost_accounting.md', 'provider/model/tokens/estimated_cost/confirmed_cost/source/status. No fabricated usage; UNKNOWN stays UNKNOWN; estimated vs confirmed separated; cost per completed task / accepted artifact / rework / duplicate-avoided.'],
  ['observability_contract.md', 'Observability Contract', '15_agent_orchestration/observability_contract.md', '14 events + 10 metrics (completion/cycle-time/retry/failure/duplicate-prevention/tokens/cost/owner-wait/verification-pass/rollback). Contracts only; no emitter.'],
  ['policy_engine.md', 'Policy Engine', '15_agent_orchestration/policy_engine.md', '14 policies incl. no-production-without-approval, no-send, no-network-unless-allowed, no-secret-without-gate, no-delete/merge-without-approval, no-task-without-done-definition, no-run-without-context-freshness, no-duplicate, no-unlimited-retry, no-unbounded-token, no-self-approval, no-claim-without-evidence, no-completion-without-verification.'],
  ['orchestration_dashboard.md', 'Orchestration Dashboard', '09_dashboards/orchestration_dashboard.md', 'Tasks, synthetic simulations, ready, waiting-dependency, waiting-owner, budget warnings, retries, failures, dead letters, verification, agent allocation, token estimates, context freshness, production-prohibited.'],
  ['owner_orchestration_command_center.md', 'Owner Orchestration Command Center', '09_dashboards/owner_orchestration_command_center.md', 'Highest-priority owner gate, highest-risk task, largest token estimate, duplicate prevented, failed verification, dead letter, task ready for safe local execution, production request intentionally blocked, next action.'],
  ['communication_monitor_reproducibility.md', 'Communication Monitor Reproducibility Note', '15_agent_orchestration/communication_monitor_reproducibility.md', 'yandex_mail_imap_read.mjs was untracked; now the read-only subset is tracked (no secrets, no real contacts, no send/flag-mutation). Read-only proven by static no-IMAP test. References were comments, not hard imports. No production runtime changed; IMAP not executed.'],
  ['what_already_exists_links.md', 'WHAT_ALREADY_EXISTS + AI System Map Links', '15_agent_orchestration/what_already_exists_links.md', 'Agent Orchestration adds the dev/knowledge-work task control plane + simulator over the existing chain. Reuses AI HQ task ledger + context pack builder; references Master Controller production queue as boundary-only. Links: tools/orchestrator_os/, tools/communication_monitor/, _generated/orchestrator_os/.'],
  ['synthetic_e2e_report.md', 'Synthetic E2E Report', '15_agent_orchestration/synthetic_e2e_report.md', '12 simulated scenarios (documentation, multi-phase code, duplicate-blocked, owner-approval, budget-exceeded, retry, terminal->dead-letter, dependency-failure, revision-conflict, handoff, production-blocked, external-comm-blocked) pass; no real agent started.'],
  ['security_boundary_report.md', 'Security Boundary Report', '15_agent_orchestration/security_boundary_report.md', 'Proves no real agent launch, no scheduler/background, no network/send/IMAP, no production access, no delete/merge, no secrets, no real contacts. Scanner catches planted violations.'],
];

mkdirSync(path.join(ROOT, SUB), { recursive: true });
let count = 0;
for (const [file, title, target, body] of DOCS) {
  const dir = target.includes('/') ? path.dirname(target) : SUB;
  mkdirSync(path.join(ROOT, dir), { recursive: true });
  const md = `---\ncanonical_target: ${target}\nrelated_project: agent-orchestration\nstatus: PROPOSED_NOT_APPLIED\nsynthetic: true\n---\n\n# ${title}\n\n${body}\n\n> Proposed canonical doc. NOT applied. Owner applies post-review via AI HQ apply flow.\n`;
  writeFileSync(path.join(ROOT, dir, file), md);
  count++;
}
console.log(`[gen-proposed-docs] wrote ${count} agent-orchestration proposed docs under docs_canonical_proposed/`);
