#!/usr/bin/env node
// tools/conversation_hub/gen_proposed_docs.mjs — generates proposed canonical docs (MP41). Read-only.
// Writes ONLY under docs_canonical_proposed/. Does NOT apply. Owner applies post-review.
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.cwd(), 'docs_canonical_proposed');
const SUB = '13_conversation_hub';

const DOCS = [
  ['conversation_hub_command_center.md', 'Conversation Hub — Canonical Note', '13_conversation_hub/conversation_hub_command_center.md', 'Conversation Hub is the omnichannel communication CONTROL PLANE: it owns the normalized conversation view, thread mapping, message normalization, classification, routing recommendations, draft-request representation, approval-request DISPLAY, opt-out recommendation, escalation, cross-channel view, and future adapter contracts. It is NEVER the canonical writer: identity/approval/reply/opt-out/send-state belong to Master Controller. It NEVER sends, connects to a network, calls SMTP/IMAP/Telegram/WhatsApp/MAX, imports real conversations, creates live drafts, or runs unofficial channel automation.'],
  ['source_of_truth_extension.md', 'Source of Truth Extension (Communication)', '13_conversation_hub/source_of_truth_extension.md', '15 communication entities with system-of-record + readers + writers + forbidden-writers. Master Controller owns canonical identity/approval/reply/opt-out/delivery/bounce. Conversation Hub owns only the normalized conversation/thread view + routing/draft recommendations. Analytics OS owns conversation metrics; Customer Success owns support lifecycle; Revenue owns deal state.'],
  ['conversation_domain_standard.md', 'Conversation Domain Standard', '13_conversation_hub/conversation_domain_standard.md', 'Conversation/Thread/NormalizedMessage/Draft/ApprovalRequest/Consent/OptOut/Attachment/Classification/Routing/ChannelHealth schemas. Direction INBOUND/OUTBOUND/INTERNAL/SYSTEM; type PLAIN/REPLY/AUTO_REPLY/BOUNCE/DELIVERY_RECEIPT/OPT_OUT/UNSUBSCRIBE/COMPLAINT/SUPPORT/BILLING/REFERRAL/SYSTEM_EVENT/UNKNOWN. Messages store redacted body + reference, never raw production body.'],
  ['channel_contract_standard.md', 'Channel Contract Standard', '13_conversation_hub/channel_contract_standard.md', 'EMAIL/TELEGRAM/WEB_FORM/MAX_FUTURE/WHATSAPP_OFFICIAL_FUTURE/PHONE_MANUAL_REFERENCE/INTERNAL. Per-channel thread semantics, reply correlation, delivery states, attachment handling, consent, opt-out, identity confidence, future adapter requirements. Prohibited: unofficial WhatsApp/MAX automation, browser automation, personal-account scraping, userbot Telegram. All channels NOT_CONNECTED in this task.'],
  ['message_normalization_policy.md', 'Message Normalization Policy', '13_conversation_hub/message_normalization_policy.md', 'Deterministic normalizer: stable IDs, UTC timestamps, redacted body + body_reference, sanitized HTML, secret/PII flagging, stable checksum, preserved source provenance. Raw body never required for analytics.'],
  ['thread_correlation_policy.md', 'Thread Correlation Policy', '13_conversation_hub/thread_correlation_policy.md', 'Email: Message-ID/In-Reply-To/References, then subject+participant fallback. Telegram: chat + reply reference (future). Web form: submission ID + campaign + explicit identity + consent. Never correlate by company name alone or by guessed email. Mirrors existing reply_correlation.mjs strategy without a duplicate store.'],
  ['identity_resolution_policy.md', 'Identity Resolution Policy', '13_conversation_hub/identity_resolution_policy.md', 'States CANONICAL/STRONG/PROBABLE/AMBIGUOUS/NO_MATCH/CONFLICT. Only canonical/strong evidence allows automatic link recommendation; probable requires owner review; conflict blocks routing. Conversation Hub NEVER creates a new canonical lead.'],
  ['classification_policy.md', 'Classification Policy', '13_conversation_hub/classification_policy.md', 'Deterministic rule engine first (RU+EN), 20 primary intents. Every classification carries confidence + matched evidence + rule trace + manual-review threshold. Optional model-assistance is a contract only; no API call.'],
  ['routing_policy.md', 'Routing Policy', '13_conversation_hub/routing_policy.md', 'price/interest/meeting->Revenue; billing->Finance; support/referral->Customer Success; incident/complaint->Executive; opt-out/bounce/auto-reply->Master Controller reply queue; unknown->owner. Identity conflict blocks routing. Conversation Hub returns recommendations only; mutates nothing.'],
  ['consent_opt_out_policy.md', 'Consent / Opt-out Policy', '13_conversation_hub/consent_opt_out_policy.md', 'Opt-out detection (explicit unsubscribe, "не пишите", "удалите контакты", consent revoked) with scopes ALL_COMMERCIAL/CHANNEL_ONLY/CAMPAIGN_ONLY/PRODUCT_ONLY/SUPPORT_EXCLUDED. Commercial opt-out blocks Growth/Revenue outreach; support may remain when contractually necessary. No automatic legal conclusion; evidence required; canonical mutation only via Master Controller; high priority.'],
  ['draft_validation_policy.md', 'Draft Validation Policy', '13_conversation_hub/draft_validation_policy.md', 'Drafts are send_allowed=false. Blocked when recipient guessed, identity conflict, opt-out, unsupported claim, product not ready, price unapproved, attachment missing, privacy violation, wrong channel, no approval requirement, expired evidence, stale product version, or no canonical reference for a non-test draft.'],
  ['approval_handoff_policy.md', 'Approval / Outbound Handoff Policy', '13_conversation_hub/approval_handoff_policy.md', 'Source OS -> Hub draft request -> validation -> owner preview -> Master Controller approval -> MC approved-send seam -> channel transport -> transport result -> MC canonical ledger -> Hub derived view. Hub never bypasses approval, calls SMTP, writes a send ledger, marks sent, infers success, or retries non-idempotently. Master Controller remains canonical approval owner.'],
  ['retry_idempotency_policy.md', 'Retry / Idempotency Policy', '13_conversation_hub/retry_idempotency_policy.md', 'Idempotency key + attempt ID + original request ID + retry count. Outbound retry only from canonical approved request, same idempotency key; no retry after ambiguous transport result without reconciliation; inbound replay deduplicated; attachment retries checksum-aware; rate-limit state preserved.'],
  ['attachment_policy.md', 'Attachment Policy', '13_conversation_hub/attachment_policy.md', 'PDF/image/document/spreadsheet/archive/unknown as File Vault references with checksum + MIME validation + size limit + sensitivity + malware-scan contract (future). No binary duplication, no automatic opening, no secret extraction, no publication. Synthetic metadata only.'],
  ['privacy_redaction_policy.md', 'Privacy / Redaction Policy', '13_conversation_hub/privacy_redaction_policy.md', 'Redact passwords/API keys/tokens/private keys/banking credentials/card numbers/IBAN/sensitive personal info/unnecessary phone+email in analytics views/special-category data. Store canonical references + masked identifiers + provenance + minimum necessary text. No raw production bodies.'],
  ['retention_policy.md', 'Retention Policy', '13_conversation_hub/retention_policy.md', 'Retention for raw envelopes (not stored), normalized messages, drafts, approvals, attachments, delivery receipts, opt-outs, summaries, analytics events, audit logs. No automatic deletion; deletion requires policy + owner approval + canonical impact review + backup consideration.'],
  ['email_contract.md', 'Email Contract', '13_conversation_hub/email_contract.md', 'SMTP transport (future) + read-only IMAP inbound (future) + Message-ID correlation + bounce classification + attachment references + subject encoding + idempotency + approval + ledger ownership (Master Controller). No SMTP/IMAP implementation or connection in this task.'],
  ['telegram_contract.md', 'Telegram Contract', '13_conversation_hub/telegram_contract.md', 'Owner control Telegram: owner-only, API-only, commands/buttons, approval views, no raw secrets (existing telegram_api_transport.mjs). Client Telegram (future): only with explicit business/legal policy, separate identity, explicit consent, NO userbot, NO personal-account automation. Not implemented here.'],
  ['web_form_contract.md', 'Web Form Contract', '13_conversation_hub/web_form_contract.md', 'Future intake: submission ID, timestamp, consent, name/company, contact, product interest, campaign ID, source, privacy version. Validation + spam detection + rate limit + consent evidence + API-only handoff. No automatic outbound reply without policy. No real form.'],
  ['max_future_contract.md', 'MAX Future Contract', '13_conversation_hub/max_future_contract.md', 'Future OFFICIAL MAX adapter only. No reverse engineering, no personal-account automation. NOT_CONNECTED. Not implemented.'],
  ['whatsapp_official_future_contract.md', 'WhatsApp Official Future Contract', '13_conversation_hub/whatsapp_official_future_contract.md', 'Official WhatsApp Business Platform ONLY. No unofficial libraries, no browser automation. Templates + consent per future applicable policy. NOT_CONNECTED. Not implemented.'],
  ['analytics_contract.md', 'Analytics Contract', '13_conversation_hub/analytics_contract.md', 'Events: conversation_created, inbound_normalized, duplicate_detected, identity_resolved, classification_completed, draft_created, approval_requested, approval_reference_updated, opt_out_detected, routing_completed, channel_failure_detected. Metrics: conversations, inbound volume, reply-required, classification confidence, manual-review rate, response/approval time, duplicate rate, unmatched identity rate, opt-out rate, channel failure rate. Contracts only; no emitter.'],
  ['master_controller_contract.md', 'Master Controller Contract', '13_conversation_hub/master_controller_contract.md', 'Master Controller is the sole canonical writer of identity/pipeline/approval/reply/opt-out/send state. Conversation Hub provides draft requests + approval display + opt-out recommendations only; it never mutates canonical state, never writes the send ledger (outbound_send_ledger.jsonl), and never mutates reply state (reply_monitor).'],
  ['conversation_dashboard.md', 'Conversation Dashboard', '09_dashboards/conversation_dashboard.md', 'Conversations, needs-reply, needs-approval, identity conflicts, opt-outs, support, billing, escalations, channel readiness (all NOT_CONNECTED), classification quality, stale conversations, owner actions, intentionally-disconnected channels. References Master Controller queues; does not duplicate them.'],
  ['owner_conversation_command_center.md', 'Owner Conversation Command Center', '09_dashboards/owner_conversation_command_center.md', 'Compact owner view: primary conversation action, highest-priority reply, approval pending, opt-out requiring review, support escalation, channel issue, identity conflict, stale thread, owner capacity warning. No message action executed.'],
  ['what_already_exists_links.md', 'WHAT_ALREADY_EXISTS + AI System Map Links', '13_conversation_hub/what_already_exists_links.md', 'Conversation Hub adds a normalized omnichannel view + classification/routing/draft-request/approval-display/opt-out-recommendation/handoff-contract layer over existing Master Controller communication code (outbound_send_ledger, reply_monitor, reply_correlation, approved_email_send_adapter, telegram_api_transport). It duplicates none of them. Links: tools/conversation_hub/, _generated/conversation_hub/.'],
];

mkdirSync(path.join(ROOT, SUB), { recursive: true });
let count = 0;
for (const [file, title, target, body] of DOCS) {
  const dir = target.includes('/') ? path.dirname(target) : SUB;
  mkdirSync(path.join(ROOT, dir), { recursive: true });
  const md = `---\ncanonical_target: ${target}\nrelated_project: conversation-hub\nstatus: PROPOSED_NOT_APPLIED\nsynthetic: true\n---\n\n# ${title}\n\n${body}\n\n> Proposed canonical doc. NOT applied. Owner applies post-review via AI HQ apply flow.\n`;
  writeFileSync(path.join(ROOT, dir, file), md);
  count++;
}
console.log(`[gen-proposed-docs] wrote ${count} conversation-hub proposed docs under docs_canonical_proposed/`);
