#!/usr/bin/env node
// tools/reliability_os/gen_proposed_docs.mjs — generates proposed canonical docs (MP53). Read-only.
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.cwd(), 'docs_canonical_proposed');
const SUB = '17_reliability';

const DOCS = [
  ['reliability_control_plane_note.md', 'Reliability Control Plane — Canonical Note', '17_reliability/reliability_control_plane_note.md', 'Reliability / Observability / Business Continuity Control Plane: service catalog, dependency graph, health contracts, SLI/SLO, error budgets, logging/metric/trace standards, alerts, incident classification, runbooks, capacity, backup/restore standards, RPO/RTO, DR, release/rollback readiness, live-verification plan. NOT a monitoring runtime/scheduler/worker/backup service. Never installs monitoring, runs live health checks, restarts services, executes backup/restore, runs load/chaos tests, sends alerts, mutates production, or claims availability/backup-safety/infra-status without live verification.'],
  ['service_catalog.md', 'Service Catalog', '17_reliability/service_catalog.md', '16 services/components with owner/criticality/runtime/dependencies/data-owned/health-contract/recovery-priority/live-verification-required.'],
  ['criticality_standard.md', 'Criticality Standard', '17_reliability/criticality_standard.md', 'TIER_0_CANONICAL..TIER_4_DEVELOPMENT_ONLY. canonical store TIER_0; API/worker/queue TIER_1; Telegram/IMAP/backup TIER_2; dashboards TIER_3; offline simulators TIER_4. Evidence-based.'],
  ['dependency_map.md', 'Dependency Map', '17_reliability/dependency_map.md', '12 dependency edges (type/critical/timeout/failure-behavior/fallback). SPOFs: vps_host (ALL_PRODUCTION), canonical_store, caddy, tls_cert, local_workstation. No cycles.'],
  ['failure_domain_model.md', 'Failure Domain Model', '17_reliability/failure_domain_model.md', '16 failure domains with affected services, blast radius, detection, containment, recovery, owner.'],
  ['health_check_standard.md', 'Health Check Standard', '17_reliability/health_check_standard.md', '8 check types. Semantic rules: liveness!=readiness, API 200!=canonical write path, timer active!=successful job, backup exists!=restorable, contract test!=live health. Synthetic marked; default live status UNKNOWN.'],
  ['master_controller_health_contract.md', 'Master Controller Health Contract', '17_reliability/master_controller_health_contract.md', '13 checks: liveness/readiness/canonical-writer-mode/canonical-readable/revision-valid/queue/worker-heartbeat/scheduler-freshness/dead-letter/autosend-state/live-send-state/backup-freshness/storage-pressure. No live requests.'],
  ['telegram_health_contract.md', 'Telegram Health Contract', '17_reliability/telegram_health_contract.md', 'Service state, one-poller invariant, heartbeat freshness, API readiness (future), canonical isolation, no local fallback, callback error rate. No Telegram API.'],
  ['imap_health_contract.md', 'IMAP Health Contract', '17_reliability/imap_health_contract.md', 'Timer freshness, last success, read-only mode, no flag mutation, TLS, bounded scan, stale warning. No IMAP call.'],
  ['backup_health_contract.md', 'Backup Health Contract', '17_reliability/backup_health_contract.md', 'Exists, interval, size, checksum, manifest, revision recorded, retention, encryption status, restore-test age, off-site. No real backup.'],
  ['android_reliability_contract.md', 'Android Reliability Contract', '17_reliability/android_reliability_contract.md', 'API reachability, cache freshness, revision conflict, no offline mutation, Room migration, stale indicator. No build changes.'],
  ['sli_catalog.md', 'SLI Catalog', '17_reliability/sli_catalog.md', '15 SLIs across Master Controller / communication / Telegram / delivery. No arbitrary live targets claimed as confirmed.'],
  ['slo_policy.md', 'SLO Policy', '17_reliability/slo_policy.md', '8 SLO proposals; statuses PROPOSED/INTERNAL_TARGET/OWNER_APPROVED/LIVE_VALIDATED/RETIRED. No production SLO compliance claimed.'],
  ['error_budget_policy.md', 'Error Budget Policy', '17_reliability/error_budget_policy.md', 'Deterministic synthetic calculation. No budget from synthetic samples as production; no release decision from one metric; integrity/security hard blocker overrides; insufficient data -> UNKNOWN.'],
  ['logging_standard.md', 'Logging Standard', '17_reliability/logging_standard.md', 'Structured fields; prohibits secrets/tokens/raw bodies/unnecessary contacts/financial credentials/special-category. Integrates Security redaction. 7 log levels.'],
  ['correlation_standard.md', 'Correlation / Trace Standard', '17_reliability/correlation_standard.md', 'request/correlation/causation/task/job/lead/conversation/project/run IDs. No personal ID as correlation ID; stable through handoff; no mandatory tracing vendor.'],
  ['metric_standard.md', 'Metric Standard', '17_reliability/metric_standard.md', '7 metric types; bounded labels; no raw email/lead-ID/error-stack labels; units explicit; synthetic marker.'],
  ['alerting_policy.md', 'Alerting Policy', '17_reliability/alerting_policy.md', '5 severities, 13 categories, 13 alert rules. auto_action default false. unexpected_send = P0 hard blocker with security handoff.'],
  ['alert_fatigue_policy.md', 'Alert Fatigue Policy', '17_reliability/alert_fatigue_policy.md', 'Deduplication, grouping, minimum duration, recovery notification, maintenance + dependency suppression, throttling, ownership, stale review. Do-not-wake P3/INFO; external channel NONE_SELECTED (owner action).'],
  ['incident_reconciliation.md', 'Incident Reconciliation', '17_reliability/incident_reconciliation.md', 'Shared incident envelope; 5 domains. Reliability lifecycle distinct from security; one event may open both with cross-linked correlation_ids. No destructive collapse.'],
  ['reliability_incident_policy.md', 'Reliability Incident Policy', '17_reliability/reliability_incident_policy.md', 'Lifecycle DETECTED..CLOSED. No actual notification.'],
  ['runbook_catalog.md', 'Runbook Catalog', '17_reliability/runbook_catalog.md', '25 runbooks (API/canonical/worker/queue/scheduler/telegram/imap/backup/restore/disk/memory/TLS/caddy/dependency/unexpected-send/corruption/VPS/workstation/git/rollback/security-handoff). Safe vs owner-gated vs dangerous separated; no live commands.'],
  ['backup_policy.md', 'Backup Policy', '17_reliability/backup_policy.md', 'Full/incremental, atomic snapshot, manifest, checksum, permissions, no secret, retention/rotation, off-site (owner), immutability, corruption detection, restore-test frequency. No off-site copy created.'],
  ['rpo_rto_policy.md', 'RPO / RTO Policy', '17_reliability/rpo_rto_policy.md', 'Per-asset proposals; statuses UNKNOWN/PROPOSED/OWNER_APPROVED/LIVE_TESTED. No approved values invented.'],
  ['restore_test_standard.md', 'Restore Test Standard', '17_reliability/restore_test_standard.md', 'Verifies source/checksum/manifest/isolated destination/schema/permissions/readability/counts/semantics/revision/no production overwrite/cleanup/report. No production restore.'],
  ['disaster_recovery_plan.md', 'Disaster Recovery Plan', '17_reliability/disaster_recovery_plan.md', '12 disaster scenarios with detection/declaration/containment/recovery-priority/restore-source/dependencies/owner-decisions/verification/fallback/communication.'],
  ['business_continuity_plan.md', 'Business Continuity Plan', '17_reliability/business_continuity_plan.md', 'Uses Executive OS continuity model. Minimum viable operation per outage. No automatic continuity activation; owner-unavailable = no autonomous commercial action.'],
  ['capacity_policy.md', 'Capacity Policy', '17_reliability/capacity_policy.md', 'CPU/RAM/disk/queue/throughput/owner-review/delivery/support capacity. Statuses CONFIRMED/SYSTEM_OBSERVED/MODEL_ESTIMATE/OWNER_TARGET/UNKNOWN. Disk critical preserves backup/atomic space; capacity can block launch/sales/campaign.'],
  ['release_readiness_gate.md', 'Release Readiness Gate', '17_reliability/release_readiness_gate.md', 'Combines security gate + integration + tests + backup + restore + rollback + health + integrity + capacity + owner approval + incidents. Hard blockers incl. unverified backup/restore, unknown canonical integrity, unknown production health, unknown owner capacity. Statuses up to OWNER_ACCEPTED_REFERENCE; no actual release approval.'],
  ['change_management.md', 'Change Management', '17_reliability/change_management.md', 'Change record (scope/services/risk/preconditions/deployment-plan/verification/rollback/window/approval). Max status READY_FOR_OWNER_REVIEW; no deployment.'],
  ['maintenance_window_standard.md', 'Maintenance Window Standard', '17_reliability/maintenance_window_standard.md', 'Affected services, start/end proposal, customer impact, backup prerequisite, owner availability, rollback deadline, communication, verification period. No schedule created.'],
  ['deployment_standard.md', 'Deployment Standard', '17_reliability/deployment_standard.md', '11 phases PRECHECK..ROLLBACK. Safety verify includes AUTOSEND=BLOCKED/SEND_ALLOWED_LIVE=OFF/one-writer/one-poller. Every deployment requires explicit owner approval; no script execution.'],
  ['rollback_standard.md', 'Rollback Standard', '17_reliability/rollback_standard.md', 'Trigger, max decision time, code/config rollback, schema/data compatibility, restart, health validation, incident record, evidence. No rollback overwrites newer canonical data blindly.'],
  ['soak_standard.md', 'Soak Standard', '17_reliability/soak_standard.md', 'Exact start/end, version, services, counters, no-change invariants, observations, invalidation, final decision. Prevents partial-pass, code change during soak, ambiguous send-count (explicit: outbound_send_ledger delta=0 under AUTOSEND=BLOCKED), missing baseline.'],
  ['production_verification_plan.md', 'Production Verification Plan', '17_reliability/production_verification_plan.md', 'FUTURE owner-executed live checks: VPS identity, service state, one canonical writer, API health, heartbeat, scheduler freshness, queue, dead letters, one poller, IMAP read-only, backups, restore evidence, Caddy/TLS, UFW/fail2ban, disk/memory, security boundaries, no-send gates. Not executed.'],
  ['reliability_dashboard.md', 'Reliability Dashboard', '09_dashboards/reliability_dashboard.md', 'Service catalog, health (all live UNKNOWN), freshness, dependencies, SLO proposals, error budgets, alerts, incidents, queue/worker/scheduler, communication, backups, restore, RPO/RTO, capacity, release readiness, owner actions, live-verification-required.'],
  ['owner_reliability_command_center.md', 'Owner Reliability Command Center', '09_dashboards/owner_reliability_command_center.md', 'Highest reliability risk (single VPS SPOF), services requiring live verification, stale component, backup/restore blocker, capacity blocker, open incident, release blocker, owner decision, next safe action.'],
  ['integration_contracts.md', 'Reliability Integration Contracts', '17_reliability/integration_contracts.md', 'Contracts with Master Controller/Telegram/IMAP/Android/Analytics/Security/Executive/Orchestration/Conversation Hub/File Vault. No runtime integration.'],
  ['source_of_truth_extension.md', 'Source of Truth Extension (Reliability)', '17_reliability/source_of_truth_extension.md', 'Reliability owns service catalog/health contracts/SLI-SLO/error-budgets/runbooks/backup-restore standards/RPO-RTO/DR/release-readiness. Analytics owns derived metrics; Security owns security incidents; Executive owns business-continuity decisions; Master Controller owns canonical operational state. No second scheduler/worker/backup/logging system.'],
  ['what_already_exists_links.md', 'WHAT_ALREADY_EXISTS + AI System Map Links', '17_reliability/what_already_exists_links.md', 'Reliability adds health/SLO/alert/runbook/backup/DR/release standards over existing systemd services + healthchecks + backup script + git bundles. Links: tools/reliability_os/, _generated/reliability_os/.'],
  ['failure_simulation_report.md', 'Failure Simulation Report', '17_reliability/failure_simulation_report.md', '16 synthetic failure injections + 18 E2E scenarios (A-R) map to detection/health/alert/runbook; none affect production. Unexpected-send + canonical-corruption are hard blockers.'],
  ['security_boundary_report.md', 'Reliability Security Boundary Report', '17_reliability/security_boundary_report.md', 'Proves the reliability_os tree: no network/live-health/process-launch/scheduler/restart/production/send-alert/delete/merge, no secret value. Self-test catches planted process launch.'],
];

mkdirSync(path.join(ROOT, SUB), { recursive: true });
let count = 0;
for (const [file, title, target, body] of DOCS) {
  const dir = target.includes('/') ? path.dirname(target) : SUB;
  mkdirSync(path.join(ROOT, dir), { recursive: true });
  const md = `---\ncanonical_target: ${target}\nrelated_project: reliability-observability\nstatus: PROPOSED_NOT_APPLIED\nsynthetic: true\n---\n\n# ${title}\n\n${body}\n\n> Proposed canonical doc. NOT applied. Owner applies post-review via AI HQ apply flow.\n`;
  writeFileSync(path.join(ROOT, dir, file), md);
  count++;
}
console.log(`[gen-proposed-docs] wrote ${count} reliability proposed docs under docs_canonical_proposed/`);
