/**
 * telegram_master_bot_hardened.mjs
 * Generated by emergency_live_fix_2026-05-27
 * Minimal live-response bot — /ping /health /sales_today /followups /replies /lead_status
 * SAFE: does NOT send to clients. Only responds to configured CHAT_ID (owner).
 */

import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const WORKSPACE  = path.resolve(path.join(__dirname, '..', '..'));

// ── ENV ───────────────────────────────────────────────────────────────────────
function parseEnvFile(p) {
  const r = {};
  if (!fs.existsSync(p)) return r;
  const raw = fs.readFileSync(p, 'utf-8').replace(/^\uFEFF/, '');
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq < 0) continue;
    const key = t.substring(0, eq).trim();
    const val = t.substring(eq + 1).trim().replace(/^["']|["']$/g, '');
    if (key) r[key] = val;
  }
  return r;
}
const envA = parseEnvFile(path.join(__dirname, '.env'));
const envB = parseEnvFile(path.join(WORKSPACE, '.env'));
const ENV  = { ...envB, ...envA };
const BOT_TOKEN = ENV.TELEGRAM_BOT_TOKEN || ENV.BOT_TOKEN || '';
const CHAT_ID   = String(ENV.TELEGRAM_CHAT_ID || ENV.TELEGRAM_ADMIN_CHAT_ID || ENV.CHAT_ID || '').trim();
const LOCK_FILE = path.join(__dirname, '.telegram_master_bot.lock');
const LOGS_DIR  = path.join(__dirname, 'logs');
const BOT_LOG   = path.join(LOGS_DIR, 'telegram_master_bot.log');
const ERR_LOG   = path.join(LOGS_DIR, 'telegram_errors.log');
const STATE_F   = path.join(__dirname, 'state', 'telegram_gateway_state.json');
const START_TS  = Date.now();

fs.mkdirSync(LOGS_DIR, { recursive: true });
fs.mkdirSync(path.dirname(STATE_F), { recursive: true });

// ── SAFE LOG ─────────────────────────────────────────────────────────────────
function botLog(level, event, data = {}) {
  const safe = {};
  for (const [k, v] of Object.entries(data)) {
    if (typeof v === 'string' && v.length > 20 && (k.toLowerCase().includes('token') || k.toLowerCase().includes('password'))) {
      safe[k] = '[REDACTED]';
    } else {
      safe[k] = v;
    }
  }
  const line = JSON.stringify({ ts: new Date().toISOString(), level, event, ...safe });
  console.log(line);
  try { fs.appendFileSync(BOT_LOG, line + '\n', 'utf-8'); } catch (_) {}
}

function appendTelegramError(msg) {
  try { fs.appendFileSync(ERR_LOG, new Date().toISOString() + ' ' + msg + '\n', 'utf-8'); } catch (_) {}
}

// ── LOCK ─────────────────────────────────────────────────────────────────────
if (fs.existsSync(LOCK_FILE)) {
  const pid = fs.readFileSync(LOCK_FILE, 'utf-8').trim();
  try { process.kill(parseInt(pid), 0); botLog('WARN', 'LOCK_ACTIVE', { pid }); process.exit(1); } catch (_) {}
  botLog('INFO', 'STALE_LOCK_REMOVED', { pid });
  fs.unlinkSync(LOCK_FILE);
}
fs.writeFileSync(LOCK_FILE, String(process.pid), 'utf-8');
botLog('INFO', 'LOCK_ACQUIRED', { pid: process.pid });

function cleanup() {
  try { if (fs.existsSync(LOCK_FILE)) fs.unlinkSync(LOCK_FILE); } catch (_) {}
  botLog('INFO', 'SHUTDOWN', { pid: process.pid });
  updateState({ polling_active: false, pid: null });
  process.exit(0);
}
process.on('SIGINT', cleanup);
process.on('SIGTERM', cleanup);
process.on('exit', () => { try { if (fs.existsSync(LOCK_FILE)) fs.unlinkSync(LOCK_FILE); } catch (_) {} });

// ── STATE ─────────────────────────────────────────────────────────────────────
function updateState(patch) {
  try {
    let st = {};
    if (fs.existsSync(STATE_F)) { try { st = JSON.parse(fs.readFileSync(STATE_F, 'utf-8')); } catch (_) {} }
    Object.assign(st, patch, { last_updated: new Date().toISOString() });
    fs.writeFileSync(STATE_F, JSON.stringify(st, null, 2), 'utf-8');
  } catch (_) {}
}

// ── HTTP TELEGRAM API ─────────────────────────────────────────────────────────
function tgReq(method, body = null, httpTimeoutMs = 15000) {
  return new Promise((resolve, reject) => {
    const postBody = body ? JSON.stringify(body) : null;
    const opts = {
      hostname: 'api.telegram.org',
      path: `/bot${BOT_TOKEN}/${method}`,
      method: body ? 'POST' : 'GET',
      headers: body ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(postBody) } : {},
      timeout: httpTimeoutMs,
    };
    const req = https.request(opts, res => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => { try { resolve(JSON.parse(data)); } catch (_) { resolve({ ok: false }); } });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('timeout')); });
    if (postBody) req.write(postBody);
    req.end();
  });
}

async function sendTelegram(chatId, text) {
  try {
    const r = await tgReq('sendMessage', { chat_id: chatId, text, parse_mode: 'HTML' });
    if (r.ok) {
      botLog('INFO', 'sent_ok', { chat_id_last4: String(chatId).slice(-4), chars: text.length });
      return true;
    } else {
      const err = r.description || JSON.stringify(r);
      botLog('ERROR', 'send_failed', { chat_id_last4: String(chatId).slice(-4), error: err });
      appendTelegramError('send_failed: ' + err);
      return false;
    }
  } catch (e) {
    botLog('ERROR', 'send_exception', { chat_id_last4: String(chatId).slice(-4), error: e.message });
    appendTelegramError('send_exception: ' + e.message);
    return false;
  }
}

// ── SALES PHASE 1 (SAFE IMPORT) ───────────────────────────────────────────────
let salesPhase1 = null;
let salesModuleStatus = 'not_loaded';
try {
  const mod = await import('./sales_commands_phase1.mjs');
  salesPhase1 = mod.handleSalesPhase1;
  salesModuleStatus = 'ok';
  botLog('INFO', 'sales_module_loaded');
} catch (e) {
  salesModuleStatus = 'error: ' + e.message.slice(0, 80);
  botLog('ERROR', 'sales_module_load_failed', { error: e.message.slice(0, 120) });
}

// ── COMMAND HANDLERS ──────────────────────────────────────────────────────────
async function handleCommand(chatId, text, update) {
  const cmd = (text || '').trim().split('@')[0].toLowerCase();
  const uptime = Math.floor((Date.now() - START_TS) / 1000);

  // A) /ping — absolute top priority
  if (cmd === '/ping') {
    await sendTelegram(chatId, '🏓 Pong! Бот работает. PID=' + process.pid + ' Uptime=' + uptime + 's');
    return;
  }

  // B) /health
  if (cmd === '/health') {
    const lockOk = fs.existsSync(LOCK_FILE);
    const msg = [
      '✅ HEALTH REPORT',
      `PID: ${process.pid}`,
      `Uptime: ${uptime}s`,
      `Lock: ${lockOk ? 'active' : 'missing'}`,
      `Polling: active`,
      `Sales module: ${salesModuleStatus}`,
      'Auto-send: OFF',
      'Client messages: BLOCKED',
    ].join('\n');
    await sendTelegram(chatId, msg);
    return;
  }

  // C) /start
  if (cmd === '/start') {
    await sendTelegram(chatId, '🤖 Telegram Master Controller v0.8-hardened\n\nКоманды:\n/ping — проверка связи\n/health — статус бота\n/sales_today — продажи сегодня\n/followups — задачи follow-up\n/replies — статус ответов\n/lead_status — статус лидов');
    return;
  }

  // D) Sales commands via phase1 module
  const SALES_CMDS = ['/sales_today', '/followups', '/replies', '/lead_status'];
  if (SALES_CMDS.includes(cmd)) {
    if (salesPhase1) {
      try {
        await salesPhase1(chatId, text, sendTelegram, WORKSPACE);
        return;
      } catch (e) {
        const errMsg = e.message.slice(0, 80);
        botLog('ERROR', 'sales_command_error', { cmd, error: errMsg });
        await sendTelegram(chatId, `⚠️ Команда ${cmd} получена, но sales module error: ${errMsg}\n/ping работает.`);
        return;
      }
    } else {
      await sendTelegram(chatId, `⚠️ Команда ${cmd} получена, но sales module не загружен: ${salesModuleStatus}\n/ping работает.`);
      return;
    }
  }

  // E) Unknown slash command — fallback (не молчать)
  if (cmd.startsWith('/')) {
    await sendTelegram(chatId, `❓ Неизвестная команда: ${cmd}\n\nДоступные: /ping /health /sales_today /followups /replies /lead_status`);
    return;
  }

  // F) Unknown text — minimal fallback
  await sendTelegram(chatId, '💬 Используйте команды: /ping /health /sales_today');
}

// ── POLLING LOOP ──────────────────────────────────────────────────────────────
let offset = 0;
let pollErrors = 0;
let totalUpdates = 0;

botLog('INFO', 'bot_starting', {
  pid: process.pid,
  chat_id_last4: CHAT_ID.slice(-4),
  commands: '/ping /health /sales_today /followups /replies /lead_status',
});

updateState({
  pid: process.pid,
  polling_active: true,
  startup_time: new Date().toISOString(),
  version: 'v0.8-hardened-emergency-2026-05-27',
  commands: ['/ping', '/health', '/sales_today', '/followups', '/replies', '/lead_status'],
});

// Send owner startup notification
try {
  if (CHAT_ID) {
    await sendTelegram(CHAT_ID, '✅ Telegram Master Controller запущен. Проверь: /ping');
    botLog('INFO', 'owner_notification_sent', { chat_id_last4: CHAT_ID.slice(-4) });
  }
} catch (e) {
  botLog('ERROR', 'owner_notification_failed', { error: e.message });
}

// Delete webhook before polling
try {
  await tgReq('deleteWebhook', { drop_pending_updates: false });
  botLog('INFO', 'webhook_deleted_before_polling');
} catch (_) {}

async function pollOnce() {
  try {
    // Long-poll: Telegram waits up to 20s, HTTP timeout 30s (must exceed long-poll)
    const r = await tgReq('getUpdates', { offset, limit: 100, timeout: 20 }, 30000);
    if (!r.ok) {
      pollErrors++;
      botLog('WARN', 'poll_not_ok', { description: r.description, errors: pollErrors });
      updateState({ last_error: r.description, polling_errors: pollErrors });
      return;
    }
    pollErrors = 0;
    updateState({ last_heartbeat: new Date().toISOString(), polling_active: true, polling_errors: 0 });

    for (const upd of (r.result || [])) {
      offset = upd.update_id + 1;
      totalUpdates++;
      const msg = upd.message || upd.edited_message;
      if (!msg) continue;

      const chatId = msg.chat?.id;
      const text   = msg.text || '';
      const chatLast4 = String(chatId).slice(-4);

      botLog('INFO', 'incoming_update', {
        text: text.slice(0, 50),
        chat_id_last4: chatLast4,
        update_id: upd.update_id,
      });

      // CHAT GUARD — owner only
      if (CHAT_ID && String(chatId).trim() !== CHAT_ID.trim()) {
        botLog('WARN', 'chat_guard_mismatch', { incoming_last4: chatLast4, expected_last4: CHAT_ID.slice(-4) });
        continue;
      }

      try {
        await handleCommand(chatId, text, upd);
        botLog('INFO', 'command_handled', { text: text.slice(0, 30), chat_id_last4: chatLast4 });
      } catch (e) {
        botLog('ERROR', 'handle_exception', { text: text.slice(0, 30), error: e.message });
        try { await sendTelegram(chatId, '⚠️ Внутренняя ошибка. /ping работает.'); } catch (_) {}
      }
    }
  } catch (e) {
    pollErrors++;
    botLog('ERROR', 'poll_exception', { error: e.message, errors: pollErrors });
    updateState({ last_error: e.message, polling_errors: pollErrors });
    await new Promise(r => setTimeout(r, 3000));
  }
}

botLog('INFO', 'polling_started', { offset });

while (true) {
  await pollOnce();
}
